### ISSUE TITLE
Kendo grid pager with local datasource

### ISSUE THREAD

**Issue by Nadynho** [kendo-labs/knockout-kendo#219]
Hello everyone,

        We are using kendo-knockout library with the grid. We are fetching paged data from the server, we bind the data with the grid, but, we are not able to make the kendo grid pager to work. We are binding the data to an observable data structure, that's why we dont use kendo.remoteDataSource.

       The main reason is that, kendo pager does not know that we fetch paged data and kendo knockout does not tell the grid that the paging of the grid is done on the server-side and the pager only calculates the number of elements found on the client-side.

       Can someone help us with this blocking issue?

Thanks,
Bogdan.

**Comment by bmsmg** [comment]
If you are binding your grid directly to an object or array, I don't know what out-of-the-box options you will have.  

My advice would be to consider using a kendo dataSource, but customize it to your situation.  Set your grid options to include serverPaging: true.  Provide your own dataSource.transport.read function to traverse your data collection - you only need to return an object containing data and a total rowcount (which I believe is optional) from a custom read.  It doesn't matter how you get the data - AJAX or a custom provider.  One of the parameters to your read function should be an object containing details about the current page being requested, sort ordering, and any filters.  These can also be customized in the transport.parameterMap function.  Use these to return the relevant data.

I think this will give you the best outcome rather than trying to get all cowboy on it, and should stay compatible with new versions of kendo.

**Comment by rniemeyer** [comment]
Closing this issue, as a solution was suggested.
