### ISSUE TITLE
Knockout-Kendo with latest version of Kendo UI

### ISSUE THREAD

**Issue by elmcherqui** [kendo-labs/knockout-kendo#248]
Hi ,
I 'd like to know if it's safe to use knockout-kendo with the latest kendo ui build (2017.2.xxx) ?
If the answer is negative , is there any alternative using kendo ui with knockoutjs ?

Thank you in advance for your answers ?

**Comment by bmsmg** [comment]
We use ko-kendo with v2017.1.223.  There were some big issues with comboboxes/dropdowns that we had to work through when upgrading from the 2015 version to the 2016 version, but since then it has been mostly "stable".  That said, it is not an upgrade you should make without thoroughly testing your app.

**Comment by elmcherqui** [comment]
Thank you for your answers !
